/*
 * Cloudflare API
 * To get started using Cloudflare's products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudflare.sdk.models;

import cloudflare.sdk.models.DigitalExperienceMonitoringHttpDetailsResponseHttpStatsHttpStatusCodeInner;
import cloudflare.sdk.models.DigitalExperienceMonitoringTestStatOverTime;
import cloudflare.sdk.models.DigitalExperienceMonitoringTestStatPctOverTime;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInner
 */
public class DigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInnerTest {
    private final DigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInner model = new DigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInner();

    /**
     * Model tests for DigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInner
     */
    @Test
    public void testDigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInner() {
        // TODO: test DigitalExperienceMonitoringHttpDetailsResponseHttpStatsByColoInner
    }

    /**
     * Test the property 'availabilityPct'
     */
    @Test
    public void availabilityPctTest() {
        // TODO: test availabilityPct
    }

    /**
     * Test the property 'colo'
     */
    @Test
    public void coloTest() {
        // TODO: test colo
    }

    /**
     * Test the property 'dnsResponseTimeMs'
     */
    @Test
    public void dnsResponseTimeMsTest() {
        // TODO: test dnsResponseTimeMs
    }

    /**
     * Test the property 'httpStatusCode'
     */
    @Test
    public void httpStatusCodeTest() {
        // TODO: test httpStatusCode
    }

    /**
     * Test the property 'resourceFetchTimeMs'
     */
    @Test
    public void resourceFetchTimeMsTest() {
        // TODO: test resourceFetchTimeMs
    }

    /**
     * Test the property 'serverResponseTimeMs'
     */
    @Test
    public void serverResponseTimeMsTest() {
        // TODO: test serverResponseTimeMs
    }

    /**
     * Test the property 'uniqueDevicesTotal'
     */
    @Test
    public void uniqueDevicesTotalTest() {
        // TODO: test uniqueDevicesTotal
    }

}
