/*
 * Cloudflare API
 * To get started using Cloudflare's products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloudflare.sdk.models;

import java.util.Objects;
import cloudflare.sdk.models.CreateAccountRulesetRuleRequestAllOfPositionOneOf;
import cloudflare.sdk.models.CreateAccountRulesetRuleRequestAllOfPositionOneOf1;
import cloudflare.sdk.models.CreateAccountRulesetRuleRequestAllOfPositionOneOf2;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.Arrays;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import cloudflare.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-22T11:31:20.290775906+01:00[Europe/London]", comments = "Generator version: 7.5.0")
public class CreateAccountRulesetRuleRequestAllOfPosition extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(CreateAccountRulesetRuleRequestAllOfPosition.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!CreateAccountRulesetRuleRequestAllOfPosition.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'CreateAccountRulesetRuleRequestAllOfPosition' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<CreateAccountRulesetRuleRequestAllOfPositionOneOf> adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf = gson.getDelegateAdapter(this, TypeToken.get(CreateAccountRulesetRuleRequestAllOfPositionOneOf.class));
            final TypeAdapter<CreateAccountRulesetRuleRequestAllOfPositionOneOf1> adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf1 = gson.getDelegateAdapter(this, TypeToken.get(CreateAccountRulesetRuleRequestAllOfPositionOneOf1.class));
            final TypeAdapter<CreateAccountRulesetRuleRequestAllOfPositionOneOf2> adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf2 = gson.getDelegateAdapter(this, TypeToken.get(CreateAccountRulesetRuleRequestAllOfPositionOneOf2.class));

            return (TypeAdapter<T>) new TypeAdapter<CreateAccountRulesetRuleRequestAllOfPosition>() {
                @Override
                public void write(JsonWriter out, CreateAccountRulesetRuleRequestAllOfPosition value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `CreateAccountRulesetRuleRequestAllOfPositionOneOf`
                    if (value.getActualInstance() instanceof CreateAccountRulesetRuleRequestAllOfPositionOneOf) {
                        JsonElement element = adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf.toJsonTree((CreateAccountRulesetRuleRequestAllOfPositionOneOf)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `CreateAccountRulesetRuleRequestAllOfPositionOneOf1`
                    if (value.getActualInstance() instanceof CreateAccountRulesetRuleRequestAllOfPositionOneOf1) {
                        JsonElement element = adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf1.toJsonTree((CreateAccountRulesetRuleRequestAllOfPositionOneOf1)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    // check if the actual instance is of the type `CreateAccountRulesetRuleRequestAllOfPositionOneOf2`
                    if (value.getActualInstance() instanceof CreateAccountRulesetRuleRequestAllOfPositionOneOf2) {
                        JsonElement element = adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf2.toJsonTree((CreateAccountRulesetRuleRequestAllOfPositionOneOf2)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: CreateAccountRulesetRuleRequestAllOfPositionOneOf, CreateAccountRulesetRuleRequestAllOfPositionOneOf1, CreateAccountRulesetRuleRequestAllOfPositionOneOf2");
                }

                @Override
                public CreateAccountRulesetRuleRequestAllOfPosition read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize CreateAccountRulesetRuleRequestAllOfPositionOneOf
                    try {
                        // validate the JSON object to see if any exception is thrown
                        CreateAccountRulesetRuleRequestAllOfPositionOneOf.validateJsonElement(jsonElement);
                        actualAdapter = adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'CreateAccountRulesetRuleRequestAllOfPositionOneOf'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for CreateAccountRulesetRuleRequestAllOfPositionOneOf failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'CreateAccountRulesetRuleRequestAllOfPositionOneOf'", e);
                    }
                    // deserialize CreateAccountRulesetRuleRequestAllOfPositionOneOf1
                    try {
                        // validate the JSON object to see if any exception is thrown
                        CreateAccountRulesetRuleRequestAllOfPositionOneOf1.validateJsonElement(jsonElement);
                        actualAdapter = adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf1;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'CreateAccountRulesetRuleRequestAllOfPositionOneOf1'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for CreateAccountRulesetRuleRequestAllOfPositionOneOf1 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'CreateAccountRulesetRuleRequestAllOfPositionOneOf1'", e);
                    }
                    // deserialize CreateAccountRulesetRuleRequestAllOfPositionOneOf2
                    try {
                        // validate the JSON object to see if any exception is thrown
                        CreateAccountRulesetRuleRequestAllOfPositionOneOf2.validateJsonElement(jsonElement);
                        actualAdapter = adapterCreateAccountRulesetRuleRequestAllOfPositionOneOf2;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'CreateAccountRulesetRuleRequestAllOfPositionOneOf2'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for CreateAccountRulesetRuleRequestAllOfPositionOneOf2 failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'CreateAccountRulesetRuleRequestAllOfPositionOneOf2'", e);
                    }

                    if (match == 1) {
                        CreateAccountRulesetRuleRequestAllOfPosition ret = new CreateAccountRulesetRuleRequestAllOfPosition();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for CreateAccountRulesetRuleRequestAllOfPosition: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public CreateAccountRulesetRuleRequestAllOfPosition() {
        super("oneOf", Boolean.FALSE);
    }

    public CreateAccountRulesetRuleRequestAllOfPosition(CreateAccountRulesetRuleRequestAllOfPositionOneOf o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateAccountRulesetRuleRequestAllOfPosition(CreateAccountRulesetRuleRequestAllOfPositionOneOf1 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public CreateAccountRulesetRuleRequestAllOfPosition(CreateAccountRulesetRuleRequestAllOfPositionOneOf2 o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("CreateAccountRulesetRuleRequestAllOfPositionOneOf", CreateAccountRulesetRuleRequestAllOfPositionOneOf.class);
        schemas.put("CreateAccountRulesetRuleRequestAllOfPositionOneOf1", CreateAccountRulesetRuleRequestAllOfPositionOneOf1.class);
        schemas.put("CreateAccountRulesetRuleRequestAllOfPositionOneOf2", CreateAccountRulesetRuleRequestAllOfPositionOneOf2.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return CreateAccountRulesetRuleRequestAllOfPosition.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * CreateAccountRulesetRuleRequestAllOfPositionOneOf, CreateAccountRulesetRuleRequestAllOfPositionOneOf1, CreateAccountRulesetRuleRequestAllOfPositionOneOf2
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance instanceof CreateAccountRulesetRuleRequestAllOfPositionOneOf) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof CreateAccountRulesetRuleRequestAllOfPositionOneOf1) {
            super.setActualInstance(instance);
            return;
        }

        if (instance instanceof CreateAccountRulesetRuleRequestAllOfPositionOneOf2) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be CreateAccountRulesetRuleRequestAllOfPositionOneOf, CreateAccountRulesetRuleRequestAllOfPositionOneOf1, CreateAccountRulesetRuleRequestAllOfPositionOneOf2");
    }

    /**
     * Get the actual instance, which can be the following:
     * CreateAccountRulesetRuleRequestAllOfPositionOneOf, CreateAccountRulesetRuleRequestAllOfPositionOneOf1, CreateAccountRulesetRuleRequestAllOfPositionOneOf2
     *
     * @return The actual instance (CreateAccountRulesetRuleRequestAllOfPositionOneOf, CreateAccountRulesetRuleRequestAllOfPositionOneOf1, CreateAccountRulesetRuleRequestAllOfPositionOneOf2)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `CreateAccountRulesetRuleRequestAllOfPositionOneOf`. If the actual instance is not `CreateAccountRulesetRuleRequestAllOfPositionOneOf`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateAccountRulesetRuleRequestAllOfPositionOneOf`
     * @throws ClassCastException if the instance is not `CreateAccountRulesetRuleRequestAllOfPositionOneOf`
     */
    public CreateAccountRulesetRuleRequestAllOfPositionOneOf getCreateAccountRulesetRuleRequestAllOfPositionOneOf() throws ClassCastException {
        return (CreateAccountRulesetRuleRequestAllOfPositionOneOf)super.getActualInstance();
    }
    /**
     * Get the actual instance of `CreateAccountRulesetRuleRequestAllOfPositionOneOf1`. If the actual instance is not `CreateAccountRulesetRuleRequestAllOfPositionOneOf1`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateAccountRulesetRuleRequestAllOfPositionOneOf1`
     * @throws ClassCastException if the instance is not `CreateAccountRulesetRuleRequestAllOfPositionOneOf1`
     */
    public CreateAccountRulesetRuleRequestAllOfPositionOneOf1 getCreateAccountRulesetRuleRequestAllOfPositionOneOf1() throws ClassCastException {
        return (CreateAccountRulesetRuleRequestAllOfPositionOneOf1)super.getActualInstance();
    }
    /**
     * Get the actual instance of `CreateAccountRulesetRuleRequestAllOfPositionOneOf2`. If the actual instance is not `CreateAccountRulesetRuleRequestAllOfPositionOneOf2`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `CreateAccountRulesetRuleRequestAllOfPositionOneOf2`
     * @throws ClassCastException if the instance is not `CreateAccountRulesetRuleRequestAllOfPositionOneOf2`
     */
    public CreateAccountRulesetRuleRequestAllOfPositionOneOf2 getCreateAccountRulesetRuleRequestAllOfPositionOneOf2() throws ClassCastException {
        return (CreateAccountRulesetRuleRequestAllOfPositionOneOf2)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to CreateAccountRulesetRuleRequestAllOfPosition
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with CreateAccountRulesetRuleRequestAllOfPositionOneOf
        try {
            CreateAccountRulesetRuleRequestAllOfPositionOneOf.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for CreateAccountRulesetRuleRequestAllOfPositionOneOf failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with CreateAccountRulesetRuleRequestAllOfPositionOneOf1
        try {
            CreateAccountRulesetRuleRequestAllOfPositionOneOf1.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for CreateAccountRulesetRuleRequestAllOfPositionOneOf1 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        // validate the json string with CreateAccountRulesetRuleRequestAllOfPositionOneOf2
        try {
            CreateAccountRulesetRuleRequestAllOfPositionOneOf2.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for CreateAccountRulesetRuleRequestAllOfPositionOneOf2 failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for CreateAccountRulesetRuleRequestAllOfPosition with oneOf schemas: CreateAccountRulesetRuleRequestAllOfPositionOneOf, CreateAccountRulesetRuleRequestAllOfPositionOneOf1, CreateAccountRulesetRuleRequestAllOfPositionOneOf2. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of CreateAccountRulesetRuleRequestAllOfPosition given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of CreateAccountRulesetRuleRequestAllOfPosition
     * @throws IOException if the JSON string is invalid with respect to CreateAccountRulesetRuleRequestAllOfPosition
     */
    public static CreateAccountRulesetRuleRequestAllOfPosition fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, CreateAccountRulesetRuleRequestAllOfPosition.class);
    }

    /**
     * Convert an instance of CreateAccountRulesetRuleRequestAllOfPosition to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

