/*
 * Cloudflare API
 * To get started using Cloudflare's products and services via the API, refer to [how to interact with Cloudflare](https://developers.cloudflare.com/fundamentals/basic-tasks/interact-with-cloudflare/), which covers using tools like [Terraform](https://developers.cloudflare.com/terraform/#cloudflare-terraform) and the [official SDKs](https://developers.cloudflare.com/fundamentals/api/reference/sdks/) to maintain your Cloudflare resources.  Using the Cloudflare API requires authentication so that Cloudflare knows who is making requests and what permissions you have. Create an API token to grant access to the API to perform actions.  To create an API token, from the Cloudflare dashboard, go to My Profile > API Tokens and select Create Token. For more information on how to create and troubleshoot API tokens, refer to our [API fundamentals](https://developers.cloudflare.com/fundamentals/api/).  Totally new to Cloudflare? [Start here](https://developers.cloudflare.com/fundamentals/get-started/).
 *
 * The version of the OpenAPI document: 4.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import invalidPackageName.JSON;

/**
 * ZarazZarazConfigBaseConsentButtonTextTranslations
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-04-22T11:29:23.936635354+01:00[Europe/London]", comments = "Generator version: 7.5.0")
public class ZarazZarazConfigBaseConsentButtonTextTranslations {
  public static final String SERIALIZED_NAME_ACCEPT_ALL = "accept_all";
  @SerializedName(SERIALIZED_NAME_ACCEPT_ALL)
  private Map<String, String> acceptAll = new HashMap<>();

  public static final String SERIALIZED_NAME_CONFIRM_MY_CHOICES = "confirm_my_choices";
  @SerializedName(SERIALIZED_NAME_CONFIRM_MY_CHOICES)
  private Map<String, String> confirmMyChoices = new HashMap<>();

  public static final String SERIALIZED_NAME_REJECT_ALL = "reject_all";
  @SerializedName(SERIALIZED_NAME_REJECT_ALL)
  private Map<String, String> rejectAll = new HashMap<>();

  public ZarazZarazConfigBaseConsentButtonTextTranslations() {
  }

  public ZarazZarazConfigBaseConsentButtonTextTranslations acceptAll(Map<String, String> acceptAll) {
    this.acceptAll = acceptAll;
    return this;
  }

  public ZarazZarazConfigBaseConsentButtonTextTranslations putAcceptAllItem(String key, String acceptAllItem) {
    if (this.acceptAll == null) {
      this.acceptAll = new HashMap<>();
    }
    this.acceptAll.put(key, acceptAllItem);
    return this;
  }

   /**
   * Object where keys are language codes
   * @return acceptAll
  **/
  @javax.annotation.Nonnull
  public Map<String, String> getAcceptAll() {
    return acceptAll;
  }

  public void setAcceptAll(Map<String, String> acceptAll) {
    this.acceptAll = acceptAll;
  }


  public ZarazZarazConfigBaseConsentButtonTextTranslations confirmMyChoices(Map<String, String> confirmMyChoices) {
    this.confirmMyChoices = confirmMyChoices;
    return this;
  }

  public ZarazZarazConfigBaseConsentButtonTextTranslations putConfirmMyChoicesItem(String key, String confirmMyChoicesItem) {
    if (this.confirmMyChoices == null) {
      this.confirmMyChoices = new HashMap<>();
    }
    this.confirmMyChoices.put(key, confirmMyChoicesItem);
    return this;
  }

   /**
   * Object where keys are language codes
   * @return confirmMyChoices
  **/
  @javax.annotation.Nonnull
  public Map<String, String> getConfirmMyChoices() {
    return confirmMyChoices;
  }

  public void setConfirmMyChoices(Map<String, String> confirmMyChoices) {
    this.confirmMyChoices = confirmMyChoices;
  }


  public ZarazZarazConfigBaseConsentButtonTextTranslations rejectAll(Map<String, String> rejectAll) {
    this.rejectAll = rejectAll;
    return this;
  }

  public ZarazZarazConfigBaseConsentButtonTextTranslations putRejectAllItem(String key, String rejectAllItem) {
    if (this.rejectAll == null) {
      this.rejectAll = new HashMap<>();
    }
    this.rejectAll.put(key, rejectAllItem);
    return this;
  }

   /**
   * Object where keys are language codes
   * @return rejectAll
  **/
  @javax.annotation.Nonnull
  public Map<String, String> getRejectAll() {
    return rejectAll;
  }

  public void setRejectAll(Map<String, String> rejectAll) {
    this.rejectAll = rejectAll;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ZarazZarazConfigBaseConsentButtonTextTranslations zarazZarazConfigBaseConsentButtonTextTranslations = (ZarazZarazConfigBaseConsentButtonTextTranslations) o;
    return Objects.equals(this.acceptAll, zarazZarazConfigBaseConsentButtonTextTranslations.acceptAll) &&
        Objects.equals(this.confirmMyChoices, zarazZarazConfigBaseConsentButtonTextTranslations.confirmMyChoices) &&
        Objects.equals(this.rejectAll, zarazZarazConfigBaseConsentButtonTextTranslations.rejectAll);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acceptAll, confirmMyChoices, rejectAll);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ZarazZarazConfigBaseConsentButtonTextTranslations {\n");
    sb.append("    acceptAll: ").append(toIndentedString(acceptAll)).append("\n");
    sb.append("    confirmMyChoices: ").append(toIndentedString(confirmMyChoices)).append("\n");
    sb.append("    rejectAll: ").append(toIndentedString(rejectAll)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accept_all");
    openapiFields.add("confirm_my_choices");
    openapiFields.add("reject_all");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("accept_all");
    openapiRequiredFields.add("confirm_my_choices");
    openapiRequiredFields.add("reject_all");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to ZarazZarazConfigBaseConsentButtonTextTranslations
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ZarazZarazConfigBaseConsentButtonTextTranslations.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ZarazZarazConfigBaseConsentButtonTextTranslations is not found in the empty JSON string", ZarazZarazConfigBaseConsentButtonTextTranslations.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ZarazZarazConfigBaseConsentButtonTextTranslations.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ZarazZarazConfigBaseConsentButtonTextTranslations` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ZarazZarazConfigBaseConsentButtonTextTranslations.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ZarazZarazConfigBaseConsentButtonTextTranslations.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ZarazZarazConfigBaseConsentButtonTextTranslations' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ZarazZarazConfigBaseConsentButtonTextTranslations> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ZarazZarazConfigBaseConsentButtonTextTranslations.class));

       return (TypeAdapter<T>) new TypeAdapter<ZarazZarazConfigBaseConsentButtonTextTranslations>() {
           @Override
           public void write(JsonWriter out, ZarazZarazConfigBaseConsentButtonTextTranslations value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ZarazZarazConfigBaseConsentButtonTextTranslations read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ZarazZarazConfigBaseConsentButtonTextTranslations given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ZarazZarazConfigBaseConsentButtonTextTranslations
  * @throws IOException if the JSON string is invalid with respect to ZarazZarazConfigBaseConsentButtonTextTranslations
  */
  public static ZarazZarazConfigBaseConsentButtonTextTranslations fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ZarazZarazConfigBaseConsentButtonTextTranslations.class);
  }

 /**
  * Convert an instance of ZarazZarazConfigBaseConsentButtonTextTranslations to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

